# Generated by Django 5.2.17 on 2026-10-02 07:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sport', models.CharField(choices=[('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('pickleball', 'Pickleball')], max_length=20)),
                ('day_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evening_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_note', models.CharField(blank=True, help_text='e.g. "per table"', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('rental', 'Equipment rental'), ('food', 'Food and drinks'), ('locker', 'Locker and towel')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sport', models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('pickleball', 'Pickleball')], help_text='Leave blank if it fits every sport.', max_length=20)),
                ('bookable_online', models.BooleanField(default=False, help_text='Show as an add-on in online booking.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('membership', 'Membership'), ('package', 'Prepaid hour package')], max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hours', models.PositiveSmallIntegerField(default=0, help_text='Hours included (packages only).')),
                ('sport', models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('pickleball', 'Pickleball')], max_length=20)),
                ('valid_days', models.PositiveSmallIntegerField(default=30)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('percent', models.PositiveSmallIntegerField()),
                ('weekdays', models.CharField(default='0,1,2,3,4', help_text='Comma-separated, Monday=0 ... Sunday=6', max_length=20)),
                ('start_hour', models.PositiveSmallIntegerField(default=6)),
                ('end_hour', models.PositiveSmallIntegerField(default=12)),
                ('sport', models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('pickleball', 'Pickleball')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_hour', models.PositiveSmallIntegerField(default=6)),
                ('close_hour', models.PositiveSmallIntegerField(default=22)),
                ('evening_start_hour', models.PositiveSmallIntegerField(default=18)),
                ('student_discount', models.PositiveSmallIntegerField(default=10)),
                ('member_discount', models.PositiveSmallIntegerField(default=10)),
                ('senior_pwd_discount', models.PositiveSmallIntegerField(default=20, help_text='Fixed at 20% by Philippine law.')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('hold_minutes', models.PositiveSmallIntegerField(default=10)),
                ('pay_deadline_hours', models.PositiveSmallIntegerField(default=24)),
                ('pay_cutoff_hours_before', models.PositiveSmallIntegerField(default=3)),
                ('peso_per_point', models.PositiveSmallIntegerField(default=100)),
                ('points_per_free_hour', models.PositiveSmallIntegerField(default=100)),
                ('points_expiry_months', models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('kind', models.CharField(default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.PositiveSmallIntegerField()),
                ('end_hour', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='reservations.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_hour'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('player_type', models.CharField(choices=[('walkin', 'Walk-in / Guest'), ('member', 'Member'), ('student', 'Student'), ('team', 'Team / League'), ('senior_pwd', 'Senior citizen / PWD')], default='walkin', max_length=12)),
                ('member_until', models.DateField(blank=True, null=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('sms_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_hour', models.PositiveSmallIntegerField()),
                ('end_hour', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_left', models.PositiveSmallIntegerField(default=0)),
                ('expires_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.membershipplan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='reservations.player')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('manage_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('start_hour', models.PositiveSmallIntegerField()),
                ('end_hour', models.PositiveSmallIntegerField()),
                ('player_type', models.CharField(choices=[('walkin', 'Walk-in / Guest'), ('member', 'Member'), ('student', 'Student'), ('team', 'Team / League'), ('senior_pwd', 'Senior citizen / PWD')], max_length=12)),
                ('players_count', models.PositiveSmallIntegerField(default=1)),
                ('court_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_note', models.CharField(blank=True, max_length=120)),
                ('free_hour_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('equipment_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Debit / credit card'), ('cash', 'Cash'), ('desk', 'Pay at the front desk'), ('package', 'Package hours')], max_length=10)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('no_show', 'No-show'), ('released', 'Released (unpaid)')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online'), ('walkin', 'Front desk'), ('league', 'League / tournament')], default='online', max_length=10)),
                ('points_redeemed', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('deadline_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.leaguebooking')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.player')),
            ],
            options={
                'ordering': ['-date', '-start_hour'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('full', '24 hrs or more: full refund'), ('half', 'Less than 24 hrs: 50% refund'), ('none', 'After start: no refund'), ('complex', 'Cancelled by the complex: full refund'), ('difference', 'Reschedule price difference')], max_length=12)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('destination', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('requested', 'Waiting for approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='requested', max_length=10)),
                ('hours_before', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.item')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('method', models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Debit / credit card'), ('cash', 'Cash'), ('desk', 'Pay at the front desk'), ('package', 'Package hours')], max_length=10)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='reservations.player')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Debit / credit card'), ('cash', 'Cash'), ('desk', 'Pay at the front desk'), ('package', 'Package hours')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='reservations.reservation')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='reservations.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('court', 'Court booking'), ('item', 'Item'), ('plan', 'Membership or package')], max_length=6)),
                ('description', models.CharField(max_length=160)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reservations.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('front_desk', 'Front desk'), ('manager', 'Manager')], default='front_desk', max_length=12)),
                ('shift', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['court', 'date'], name='reservation_court_i_add3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
    ]
